version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    container_name: afyaconnect-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: afyaconnect
      POSTGRES_USER: afyaconnect_user
      POSTGRES_PASSWORD: ${DB_PASSWORD:-changeme123}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    networks:
      - afyaconnect-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U afyaconnect_user -d afyaconnect"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: afyaconnect-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 5000
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: afyaconnect
      DB_USER: afyaconnect_user
      DB_PASSWORD: ${DB_PASSWORD:-changeme123}
      JWT_SECRET: ${JWT_SECRET:-your-super-secret-jwt-key}
      GOOGLE_AI_API_KEY: ${GOOGLE_AI_API_KEY}
    volumes:
      - ./backend/uploads:/app/uploads
    depends_on:
      db:
        condition: service_healthy
    networks:
      - afyaconnect-network
    healthcheck:
      test: ["CMD", "node", "healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend React App
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: afyaconnect-frontend
    restart: unless-stopped
    networks:
      - afyaconnect-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Nginx Reverse Proxy
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: afyaconnect-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - frontend
    networks:
      - afyaconnect-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  db_data:
    driver: local

networks:
  afyaconnect-network:
    driver: bridge